### ISSUE TITLE
Source code is all rights reserved, not open source

### ISSUE THREAD

**Issue by ghost** [ARSFI/Winlink-Compression#1]
Hi there. Thanks for posting this compression source code.

Unfortunately, without a free & open source license, it has a legal status of "all rights reserved" by the author(s) and is unusable by the general public.

Will you consider releasing this code as open source? https://choosealicense.com/ is a good guide at choosing the correct license for your desired outcome. And for more information about what happens if the code remains published without a license, please see: https://choosealicense.com/no-permission/

Thanks for your consideration!

**Comment by w3qalor** [comment]
Hi Michael,

Thanks for your note. This was an oversight. You’ll find the license is properly in place now.

Best,

Lor Kutchins,
Amateur Radio Safety Foundation, Inc.

**Comment by ghost** [comment]
Thanks for your prompt response!

For those coming across this and curious to learn more about the license that was just posted: https://tldrlegal.com/license/bsd-3-clause-license-(revised)
